inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rspec
  
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
