inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rspec
  
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
