---
name: GitHub bulk issue creator
description:
  Bulk opens batches of issues across GitHub repositories based on a template
  and CSV of values.

inputs:
  write:
    required: false
    description: Write issues to GitHub, defaults to preview only
  comment:
    required: false
    description: Create comments instead of issues
  template_path:
    required: false
    description: Path to the template file
  csv_path:
    required: false
    description: Path to the CSV file
  github_token:
    required: false
    description: GitHub Token for authenticating with GitHub
