name: GitHub bulk issue creator
description: Bulk opens batches of issues across GitHub repositories based on a template and CSV of values.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.write }}
    - ${{ inputs.comment }}
    - ${{ inputs.add-to-project }}
    - ${{ inputs.project-id }}
inputs:
  write:
    required: false
    description: Write issues to GitHub, defaults to preview only
  comment:
    required: false
    description: Create comments instead of issues
  add-to-project:
    required: false
    description: Add newly created issues to a project (beta) project
  project-id:
    required: false
    description: Node ID of the project to add issues to
