#!/usr/bin/env ruby

require 'terminal-table'
require 'yaml'

regex = /\[--(.*?)((?:=.*)?)\].*\#\s*(.*)/
output = `bundle exec ./bin/bulk-issue-creator help create`
matches = output.scan(regex)

rows = []
inputs = {}
headings = ['Command line', 'GitHub Actions `with:`', 'GitHub Actions `env:`', 'Description']
matches.each do |match|
  arg = match[1] != ''
  description = match[2]

  cli = "--#{match[0]}"
  actions = match[0].tr('-', '_')
  env = match[0].tr('-', '_').upcase

  inputs[actions] = { "required" => false, "description" => description }

  cli << "=#{env}" if arg
  if arg
    actions << ": #{env}"
    env << ": #{env}"
  else
    actions << ': true'
    env << ': true'
  end


  rows << [cli, actions, env].map { |c| "`#{c}`" }.push(description)
end

table = Terminal::Table.new rows: rows, headings: headings, style: { border: :markdown }

readme = File.read('./README.md')
delim = "<!-- Options here -->"
readme = readme.gsub(/#{Regexp.escape(delim)}.*?####/m, "#{delim}\n#{table}\n\n####")
File.write('./README.md', readme)

actions_yml = YAML.load_file("./action.yml")
actions_yml["inputs"] = inputs
File.write('./action.yml', YAML.dump(actions_yml))
