name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI Tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run tests
        run: script/cibuild

  integration:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - name: Checkout template and data
        uses: actions/checkout@v2
      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSV_PATH: ./spec/fixtures/data.csv
          TEMPLATE_PATH: ./spec/fixtures/template-with-front-matter.md.mustache
