name: Integration test

on:
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - name: Checkout fixtures
        uses: actions/checkout@v3
        with:
          repository: benbalter/bulk-issue-creator-tests
          
      - name: Dry run
        uses: benbalter/bulk-issue-creator@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CSV_PATH: ./data.csv
          TEMPLATE_PATH: ./template-with-front-matter.md.mustache
          
      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CSV_PATH: ./data.csv
          TEMPLATE_PATH: ./template-with-front-matter.md.mustache
          WRITE: true

