name: Integration test

on:
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - name: Download data fixture
        run: |
          curl -O https://raw.githubusercontent.com/benbalter/bulk-issue-creator/main/spec/fixtures/data.csv

      - name: Download template fixture
        run: |
          curl -O https://raw.githubusercontent.com/benbalter/bulk-issue-creator/main/spec/fixtures/template-with-front-matter.md.mustache

      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSV_PATH: ./data.csv
        with:
          template_path: ./template-with-front-matter.md.mustache
