name: Integration test

on:
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - name: Checkout fixtures
        uses: actions/checkout@v2
        with:
          ref: fixtures
          
      - name: Create bulk issues
        uses: benbalter/bulk-issue-creator@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSV_PATH: ./data.csv
        with:
          template_path: ./template-with-front-matter.md.mustache
