name: Super Linter

on:
  push: {}
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v6.0.0
        env:
          # VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: tsconfig.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
